### PR TITLE
Refactoring codebase

### PR DESCRIPTION
**Pull request by alaxalves**
Part of https://github.com/publiclab/spectral-workbench/issues/506

### CODE REVIEW

**Comment by icarito** [comment]
I'm not an expert Ruby programmer so I'm not sure what the best practices are here.
A comment that I think the headers belong in every file, you've moved them to the controller from `app.rb`.
If ruby developers prefer this structure it will be up the the development team although I wrote this app initially.
I'm not sure I understand the logic for the split, perhaps a note in the header to explain would help to understand what is where. Thanks.

**Comment by jywarren** [comment]
Hi, if Sinatra makes the recommendation of this code organization then I'm in support, thank you! It largely matches the Ruby on Rails style of directory structure. I agree with @icarito that perhaps we should link to the Sinatra recommendation by way of explanation, perhaps also in the readme? 

Thank you!

**Comment by jywarren** [comment]
I guess I'll go ahead and merge this and if you could drop in the link in the description at top that'd be great! Thanks!

**Comment by jywarren** [comment]
Hi @alaxalves just wanted to mention that in this repo, once the `main` branch is updated, the production container auto-reboots with the new code. 🎉

**Pull request merged**
