### PR TITLE
Try fixed branch [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by jywarren**

### CODE REVIEW

**Comment by jywarren** [comment]
Noting to @icarito, if this is the next thing to merge?

**Comment by jywarren** [comment]
Re: https://travis-ci.com/publiclab/mapknitter-exporter-sinatra/builds/108205469 and https://github.com/publiclab/mapknitter-exporter/pull/11

**Comment by icarito** [comment]
Yes I merged it already https://github.com/publiclab/mapknitter-exporter/pull/11 along with https://github.com/publiclab/mapknitter-exporter/pull/13 and https://github.com/publiclab/mapknitter-exporter/pull/13/ and even https://github.com/publiclab/mapknitter-exporter/pull/14 which finally made sinatra AND minitest @ mapknitter-exporter happy. :surfing_man:

**Comment by icarito** [comment]
Btw this now means main branch is building and working using the gem's main branch! (at a specific revision, see Gemfile.lock).

**Comment by icarito** [comment]
Also here's the latest version running:
https://mapknitter-exporter-d6yfsgjd2q-uc.a.run.app/

**Pull request closed without merging**
