### PR TITLE
Setup GitHub Actions

### PR DESCRIPTION
**Pull request by aliciapaz**
Migrating to Travis for CI

- [x] Exporter Tests
- [x] Rubocop
- [x] Docker Build

### CODE REVIEW

**Comment by jywarren** [comment]
@icarito will this trigger a rebuild? Maybe we should do on a day we're online?

Looks awesome @aliciapaz!!!

**Comment by jywarren** [comment]
Oh odd, looks like an error but it didn't return it!

```
examples, 0 failures

/home/runner/work/mapknitter-exporter-sinatra/mapknitter-exporter-sinatra/lib/export.rb:74:in `save': undefined method `files' for nil:NilClass (NoMethodError)
	from /home/runner/work/mapknitter-exporter-sinatra/mapknitter-exporter-sinatra/vendor/bundle/ruby/2.4.0/gems/mapknitter-exporter-1.0.9/lib/mapknitterExporter.rb:329:in `run_export'
```

**Comment by jywarren** [comment]
Does it need the ruby files class included? Or something?

**Comment by icarito** [comment]
Indeed the trigger is set for `main` branch. We could change it to `stable`
branch to keep in line with other repositories.
--
Sebastian Silva

**Comment by aliciapaz** [comment]
Thank you both!

> Indeed the trigger is set for `main` branch. We could change it to `stable` branch to keep in line with other repositories.

@icarito! Where is this change to be done?

**Comment by icarito** [comment]
We're using the Google Cloud Build service to monitor the repo and trigger
builds. This is something that needs to be configured at the Google Cloud
Console by a privileged user (I could do it, just need confirmation).

Thanks for working on this!
--
Sebastian Silva

**Comment by aliciapaz** [comment]
> Oh odd, looks like an error but it didn't return it!
> 
> ```
> examples, 0 failures
> 
> /home/runner/work/mapknitter-exporter-sinatra/mapknitter-exporter-sinatra/lib/export.rb:74:in `save': undefined method `files' for nil:NilClass (NoMethodError)
> 	from /home/runner/work/mapknitter-exporter-sinatra/mapknitter-exporter-sinatra/vendor/bundle/ruby/2.4.0/gems/mapknitter-exporter-1.0.9/lib/mapknitterExporter.rb:329:in `run_export'
> ```

> Does it need the ruby files class included? Or something?

I think not...it looks more like something is nil in a moment when it shouldn't. I noticed when debugging that the `@directory` variable is nil after is created inside the initialize method of Export.rb (line 36), and it is as well when the `export.save` call is made.

**Comment by jywarren** [comment]
> I think not...it looks more like something is nil in a moment when it shouldn't. I noticed when debugging that the `@directory` variable is nil after is created inside the initialize method of Export.rb (line 36), and it is as well when the `export.save` call is made.

Ah ok, does this need some further debugging then? Was this error happening same way in Travis?

@icarito i think once @aliciapaz confirms this is good to go, we can just merge it and manually monitor and test an export, just to be sure. I guess someday we should make it republish /only/ if we bump the version or something, or switch it to stable, but it's really not that important, this service is basically completely stable.

**Comment by icarito** [comment]
Agreed. 👍
--
Sebastian Silva

**Comment by aliciapaz** [comment]
Yes, this is a Travis run from about a year ago:
https://app.travis-ci.com/github/publiclab/mapknitter-exporter-sinatra/jobs/423729539

So yes, we're good to go 👍🏽
Thanks!!

**Comment by jywarren** [comment]
OK Great - i'll open an issue for this just to track but it seems harmless with @aliciapaz's confirmation - here's the old Travis log that's exactly the same; the tests pass even though it shows this error, and the error does not disrupt the actual export:

```
undefined method `files' for nil:NilClass (NoMethodError)
	from /home/travis/build/publiclab/mapknitter-exporter-sinatra/vendor/.bundle/ruby/2.4.0/gems/mapknitter-exporter-1.0.9/lib/mapknitterExporter.rb:329:in `run_export'
	from /home/travis/build/publiclab/mapknitter-exporter-sinatra/app/controllers/export_controller.rb:73:in `block in run_export'
	from /home/travis/build/publiclab/mapknitter-exporter-sinatra/app/controllers/export_controller.rb:71:in `fork'
	from /home/travis/build/publiclab/mapknitter-exporter-sinatra/app/controllers/export_controller.rb:71:in `run_export'
	from /home/travis/build/publiclab/mapknitter-exporter-sinatra/app/controllers/export_controller.rb:35:in `block in <top (required)>'
```

**Pull request merged**
