### PR TITLE
Adding gitpod configs

### PR DESCRIPTION
**Pull request by alaxalves**
Available at: https://f2007ef8-cb66-41f9-9d0a-c38147b5dcb5.ws-us02.gitpod.io/#/workspace/mapknitter-exporter-sinatra

### CODE REVIEW

**Comment by cesswairimu** [comment]
Hi @alaxalves  does this repo have an interface? at gitpod no interface is displayed

**Comment by alaxalves** [comment]
> Hi @alaxalves does this repo have an interface? at gitpod no interface is displayed

Actually it doesn't have an interface, that's how it should be :D

**Comment by jywarren** [comment]
awesome folks! Thanks!!!

**Comment by jywarren** [comment]
Perhaps we could add an `index.html` page that links to the README and suggests a demo route like: http://export.mapknitter.org/export?url=https://mapknitter.org/maps/pvdtest/warpables.json&scale=30 or something?

**Comment by alaxalves** [comment]
@jywarren It's a nice idea, I'll take a look on that. Thx for the tip

**Pull request merged**
