### PR TITLE
Using ruby's official image on Dockerfile

### LINKED ISSUE #54: Use official Ruby image as base from Dockerfile
Currently we use a `debian:buster` image and install all dependencies there, including Ruby. We should use the community standard and setup an image that uses rubys's official release image

### PR DESCRIPTION
**Pull request by alaxalves**
Fixes #54 

I'd like to get #58 merged before merging this, since we'll be able to test this out more properly.

### CODE REVIEW

**Comment by icarito** [comment]
But why?
Debian gives us very long support. They actually backport security 
patches. I'm in favor of sticking to Debian where possible, unless 
there's a compelling reason to switch.

**Comment by jywarren** [comment]
Hmm. Does `ruby:2.4.6-buster` have the same backports, and is there a difference in the speed or schedule of releases that would present pros/cons? 

@alaxalves are there any cons you can think of so we can understand any tradeoffs well? Thank you both for thoroughness!

**Comment by jywarren** [comment]
Just wondering if you'd had a moment to think on this, @alaxalves ! Thanks a ton!!!

**Comment by alaxalves** [comment]
> Just wondering if you'd had a moment to think on this, @alaxalves ! Thanks a ton!!!

I'll do this for sure. I just had been focusing on other activities lately

**Comment by alaxalves** [comment]
The backport supporting is the same, the Ruby community is as wide as the Debian community. I'm closing this since it feels it does not aggregate much for the project

**Comment by jywarren** [comment]
Thanks, Alax! Appreciate it!

**Pull request closed without merging**
