### PR TITLE
Process in the background + status.json

### LINKED ISSUE #12: Respond to export request immediately and work "in the background"

### PR DESCRIPTION
**Pull request by icarito**
This allows Sinatra to reply immediately (but it should still point to the right location for status.json - when we have it).

Fixes #12

### CODE REVIEW

**Comment by icarito** [comment]
I've added another commit to fix #4 - now only the Google Cloud storage bit is left!

**Comment by jywarren** [comment]
Awesome. We need to finish the slightly complex #9 but then this should be perfect. Thanks!

**Comment by jywarren** [comment]
Oops. Reopening.

**Comment by jywarren** [comment]
This is weird, one is failing but the other is not. I think the `pid` generation is non-deterministic? Or, maybe pids are not independent across travis docker containers? Is it possible that we're always seeing pid 8 and 9 because they're run on the same physical machine?

```

  1) Mapknitter Exporter returns a JPG URL from the /export GET method
     Failure/Error: expect(last_response.body).to match("/pid/9/status.json")
       expected "/pid/8/status.json" to match "/pid/9/status.json"
     # ./spec/landing_spec.rb:33:in `block (2 levels) in <top (required)>'
```

**Comment by jywarren** [comment]
We could alternatively set the unique id independently with a timestamp or something...

**Pull request merged**
