### PR TITLE
Add initial support for cloud storage

### PR DESCRIPTION
**Pull request by icarito**
This adds the Fog gem and sets up the export to access cloud files

### CODE REVIEW

**Comment by jywarren** [comment]
Hmm...

```

Installing nokogiri 1.10.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
current directory:
/app/vendor/bundle/ruby/2.5.0/gems/nokogiri-1.10.0/ext/nokogiri
/usr/bin/ruby2.5 -r ./siteconf20190430-5-1hbksc8.rb extconf.rb
checking if the C compiler accepts ... yes
Building nokogiri using packaged libraries.
Using mini_portile version 2.4.0
checking for gzdopen() in -lz... no
zlib is missing; necessary for building libxml2
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.
```

**Comment by icarito** [comment]
Yes, I'm trying to get bundler to use the debian-packaged nokogiri and gems, if only for speed of testing but also reliability...

**Comment by icarito** [comment]
Finally! So this is the initial implementation of Google Cloud Storage including environment variables (already tested locally)!
I'll rebase when other issues are fixed! Exciting!
Note the API follows http://fog.io/storage/ and is Cloud-provider independent! ;-)

**Comment by jywarren** [comment]
Noting this very very tiny image and map, for faster testing purposes: https://export.mapknitter.org/export?url=https://mapknitter.org/maps/pvdtest/warpables.json&scale=30

**Comment by jywarren** [comment]
It gets all the way to tiling, and then the container shuts down and we can't load status.json anymore!

**Comment by jywarren** [comment]
Checklist to complete:

* [ ] return new `status.json` url from remote gcloud
* [ ] confirm pid vs. timestamp is OK

... anything else?

**Comment by icarito** [comment]
I've tested this now and will merge it! @jywarren :crossed_fingers:

**Comment by jywarren** [comment]
Wow you were up late!!!

**Comment by jywarren** [comment]
Follow-up in #27

**Pull request merged**
